### ISSUE TITLE
not work ! services not restart when been killed 

### ISSUE THREAD

**Issue by rmGFW** [FedericoPonzi/Horust#121]
i pull the latest code from master and build it 

here is the configuration i used 
```toml
command = "top -b"
working-directory = "/tmp/"
start-delay = "0s"
[restart]
strategy = "always"
```
then i run horust and kill the top process , waiting ... but i found that the top do not restart
