### ISSUE TITLE
[environment] keep-env = true

### ISSUE THREAD

**Issue by cataggar** [FedericoPonzi/Horust#217]
> keep-env = bool: default: true. Pass over all the environment variables. 
https://federicoponzi.github.io/Horust/

The default appears to be `keep-env = false`. The environment variables were not passed to the command until I added:
``` toml
[environment]
keep-env = true
```

`/etc/horust/services/azure-functions-host.toml
``` toml
command = "dotnet /azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost.dll"
[restart]
strategy = "on-failure"
backoff = "5s"
attempts = 10
[failure]
strategy = "shutdown"
```
